### ISSUE TITLE
Decide on Roles

### ISSUE THREAD

**Issue by sthmpsn** [sthmpsn/Web-Dev-Alliance#2]
Who wants to do what aspect on the project

**Comment by bryanbloomquist** [comment]
My strongest skill is front end work, so I can work on that if no one else wants to

**Comment by sthmpsn** [comment]
Bryan - UI
Ashlen - Front-end / User interactivity
Scott - Storyboarding concept / Question logic
John - Database / Login
Steve - Database / Login
